### PR TITLE
Added comment cleanup script

### PR DESCRIPTION
**Pull request by stefan-milanovic**
Note: This script was written to clean up .tsv files generated by [Google Sheets](https://www.google.com/sheets). 

To provide adequate input for this script, just copy the required sheet from Excel straight into a blank Google Sheet page. After that, download the Google Sheet and save it as a .tsv file. If you don't want to adjust the code, name the file "input.tsv" and run the program. The output file will be named "output.tsv".

### CODE REVIEW

**Review by marko-hudomal — APPROVED** [review]

**Review by beca13 — APPROVED** [review]

**Review by maricak — COMMENTED** [review]
Works great for removing *, but there are other use cases that should be implemented:
- remove blanks(" ", "\n", "\t",...) from the beginning and the end of the lines/comments.
- remove // which are used for inline comments (maybe not from the Code comments where there is an inline comment that is commented out).
- remove | at the beginning and maybe end of the lines.
- remove ---------- which are used to separate sections.

Maybe there are some other cases. You should test this code on the "anotirani" inside "sredjeni komentari.xlsx".

**Comment by stefan-milanovic** [comment]
@maricak Thanks for the notice. Fixed. Give it a try and let me know if there are more edge cases to be covered.

**Review by maricak — APPROVED** [review]
Looks good!
Can you put these files in some folder if they are not in one already?

**Comment by stefan-milanovic** [comment]
They're already in a folder called "comment_cleanup".

**Pull request merged**
